server:
  port: 18086

mocker-service:
  ribbon:
    listOfServers: mocker-service:18086

#Below is test conf, also above line needs to be uncommented for actual service

#feign:
#  hystrix:
#    enabled: true
#eureka:
#  client:
#    enabled: false
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 10000
#ribbon:
#  ReadTimeout: 10000
#bookstore-server:
#  ribbon:
#    listOfServers: http://localhost:8080
